/// <reference types="astro/client" />

// worker-configuration.d.ts (generated by `wrangler types`) declares
// Cloudflare.Env — the type of `env` imported from 'cloudflare:workers' —
// for every binding in wrangler.jsonc. Secrets aren't in wrangler.jsonc, so
// they're added here via interface merging.
declare namespace Cloudflare {
  interface Env {
    ADMIN_PASSWORD_HASH: string;
    R2_ACCESS_KEY_ID: string;
    R2_SECRET_ACCESS_KEY: string;
    R2_ACCOUNT_ID: string;
  }
}
